### ISSUE TITLE
Add support for quantized models

### ISSUE THREAD

**Issue by nchapman** [nchapman/nebula#1]
We might already be doing this but just in case let's standardize on this quantized version of the mistral 7b model for now. The gguf format is the standard format for the the quantized models that work with llama.ccp. Let's support that format.

https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/blob/main/mistral-7b-instruct-v0.2.Q5_K_M.gguf

**Comment by CodeOK1993** [comment]
Run this
`cargo run --release --features cuda -- --prompt 'Write helloworld code in Rust' --sample-len 150  --quantized --llama --model-id 'TheBloke/Mistral-7B-Instruct-v0.2-GGUF' --model-path 'mistral-7b-instruct-v0.2.Q5_K_M.gguf'`
