### ISSUE TITLE
Benchmark performance between llama.cpp and our implementation

### ISSUE THREAD

**Issue by nchapman** [nchapman/nebula#2]
Ideally we'd just create a tool that lives in the repo that would let us compare performance to other frameworks. For now let's start with just comparing with llama.cpp. Let's use the model specified in issue #1 for comparison.

**Comment by andriikrainii** [comment]
@nchapman , your input is needed - if this ticket is still relevant or we're not going to use Llama CPP
@iKachaykin  FYI

**Comment by nchapman** [comment]
@andriikrainii This is no longer necessary.
