### ISSUE TITLE
Create a Rust API for chat completions

### ISSUE THREAD

**Issue by nchapman** [nchapman/nebula#3]
Create an simple Rust API that will be used by the Pulsar desktop app for chat completions. This should eventually support multiple LLMs. This API should be inspired by the OpenAI APIs. For now this API only needs to support our [quantized mistral reference model.](https://github.com/nchapman/nebula/issues/1)

**OpenAI Docs**
This includes a mix of docs on their Python library and REST endpoint. Our inspiration should be the Python library.

https://platform.openai.com/docs/guides/text-generation/chat-completions-api

**Example models to be supported in the future**

- [LLaMA and LLaMA-v2](https://github.com/huggingface/candle/blob/main/candle-examples/examples/llama): general LLM, includes the SOLAR-10.7B variant.
- [Falcon](https://github.com/huggingface/candle/blob/main/candle-examples/examples/falcon): general LLM.
- [Gemma](https://github.com/huggingface/candle/blob/main/candle-examples/examples/gemma): 2b and 7b general LLMs from Google Deepmind.
- [Phi-1, Phi-1.5, and Phi-2](https://github.com/huggingface/candle/blob/main/candle-examples/examples/phi): 1.3b and 2.7b general LLMs with performance on par with LLaMA-v2 7b.
- [StableLM-3B-4E1T](https://github.com/huggingface/candle/blob/main/candle-examples/examples/stable-lm): a 3b general LLM pre-trained on 1T tokens of English and code datasets. Also supports StableLM-2, a 1.6b LLM trained on 2T tokens, as well as the code variants.
- [Mistral7b-v0.1](https://github.com/huggingface/candle/blob/main/candle-examples/examples/mistral): a 7b general LLM with better performance than all publicly available 13b models as of 2023-09-28.
- [Mixtral8x7b-v0.1](https://github.com/huggingface/candle/blob/main/candle-examples/examples/mixtral): a sparse mixture of experts 8x7b general LLM with better performance than a Llama 2 70B model with much faster inference.
- [StarCoder](https://github.com/huggingface/candle/blob/main/candle-examples/examples/bigcode) and [StarCoder2](https://github.com/huggingface/candle/blob/main/candle-examples/examples/starcoder2): LLM specialized to code generation.

**Comment by Warefoxe** [comment]
make http server for listening requests and start implementin main traits

suppose need 2 days more to finish API server with 1st model
