### ISSUE TITLE
Support llava 1.6 models

### ISSUE THREAD

**Issue by nchapman** [nchapman/nebula#4]
We will need vision support for a number of features in Pulsar. The llava models are the best choice for doing this right now. Unfortunately there aren't any examples of using the llava models with Candle so we'll need to investigate. Here's some more information to get started.

**Blog Post with details about the model**
https://llava-vl.github.io/blog/2024-01-30-llava-next/

**Quantized mistral-based 7b model**
https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf/blob/main/llava-v1.6-mistral-7b.Q4_K_M.gguf

**llama.cpp discussion on implementing llava 1.6**
https://github.com/ggerganov/llama.cpp/pull/5267

**Comment by iKachaykin** [comment]
@nchapman I see that you refer to HuggingFace page with llava 1.6 checkpoints that seem to be unofficial. On GitHub they mention another one: https://huggingface.co/collections/liuhaotian/llava-16-65b9e40155f60fd046a5ccf2
A readme that llava developers have in their repo: https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md#llava-v16

Is there any specific reason for that or it was non-intentional? 😄

**Comment by nchapman** [comment]
It was intentional, but I should have explained more! Because we want to run these models locally, we need them to be as memory efficient as possible which means we need to use quantized models. Generally, it is 3rd parties (often [TheBloke](https://huggingface.co/TheBloke)) that are doing this. In the case of Llava 1.6, the ones I linked to were the best ones that I've found so far. You can see the different levels of quantization for that model here:

https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf

**Comment by iKachaykin** [comment]
@nchapman got it now, great thanks a lot for this explanation!

**Comment by iKachaykin** [comment]
@nchapman I share my feedback about this task here for now, please let me know if I should put it somewhere else in the future.

I carefully investigated how other models examples are running with candle. All of them have their Rust re-implementations inside the candle repo, for example [llama](https://github.com/huggingface/candle/blob/main/candle-transformers/src/models/llama.rs), [bert](https://github.com/huggingface/candle/blob/main/candle-transformers/src/models/bert.rs), [mistral](https://github.com/huggingface/candle/blob/main/candle-transformers/src/models/mistral.rs) etc. I believe this is how it is done in general: when they want to add some new model support, some developer just re-implement the model itself from scratch on Rust and configure it in main.rs of corresponding example. I created a question in candle repo to double check this feeling: https://github.com/huggingface/candle/discussions/1842

What options do we have in that case to support these models in nebula? Ideas:
- Re-implement LLava model with candle, i.e. translate it from Python to Rust. Maybe our top choice, but it is in general quite a big task to complete. Anyway, we can do it if you think that it is a correct way to proceed.
- Run it using llama.cpp and [rust bindings](https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#:~:text=to%20existing%20clients.-,Bindings%3A,-Python%3A%20abetlen). I tested it without bindings on my PC: it worked well with a gguf file that you referred above. I am a bit not sure however, how good does this option work for you as I believe our priority was to use candle as much as possible. But this option is of course faster, as we don't need to implement the model itself.

It seems to be it for now, I really look forward for your feedback, and please let me know if you have any question!

**Comment by nchapman** [comment]
Yeah I think this is going to be an ongoing dilemma between using candle directly vs using something like llama.cpp or whisper.cpp. I did some additional investigation into candle today to see other issues that are being mentioned, and I saw various references to performance not being as good in candle as llama.cpp. That's definitely going to be a problem for us.

I believe that at some point candle will be competitive, but I'm worried in the short term it will cause us a lot more trouble and work. I think we should use whatever is the best library for the job so that we can go as fast as possible and benefit from the community contributions. @iKachaykin will you experiment with the rust bindings for llama.cpp and llava to see if you can pass and image and text to it to get a response?

@Warefoxe I think this means we should use llama.cpp wherever possible instead of candle. we might still use candle for other models but based on what I know right now, it feels like a safe bet for us to use llama.cpp as much as possible. The goal will still be to wrap these up in an easy to use library. How does this sound to you?

**Comment by iKachaykin** [comment]
@nchapman thanks for your feedback! I think relying on llama.cpp as much as possible is a good idea, in particular if it has better performance than candle. Sure, I will experiment with rust bindings for llama.cpp then, and will report about all of the results that I achieve :)

**Comment by nchapman** [comment]
@iKachaykin I'm going to assign this to @Warefoxe instead. He's making good progress with llama.cpp so let's have him run with this one and you can [take a look at whisper.cpp instead](https://github.com/nchapman/nebula/issues/4).
